### ISSUE TITLE
Training error: change config.size to [256, 256] result in error

### ISSUE THREAD

**Issue by alaliqing** [NM512/dreamerv3-torch#12]
Thank you for your work. I met the following errors when I changed the config size to [256, 256], could you help me?

```
Start evaluation. 
Traceback (most recent call last):
  File "dreamer.py", line 445, in <module>
    main(parser.parse_args(remaining))
  File "dreamer.py", line 408, in main
    tools.simulate(eval_policy, eval_envs, episodes=config.eval_episode_num)
  File "/disk/users/jk639/Jing_ws/rl_rule_exceptions/dreamerv3-torch/tools.py", line 147, in simulate
    action, agent_state = agent(obs, done, agent_state, reward)
  File "dreamer.py", line 103, in __call__
    policy_output, state = self._policy(obs, state, training)
  File "dreamer.py", line 121, in _policy
    latent, _ = self._wm.dynamics.obs_step(
  File "/disk/users/jk639/Jing_ws/rl_rule_exceptions/dreamerv3-torch/networks.py", line 229, in obs_step
    x = self._obs_out_layers(x)
  File "/disk/no_backup/jk639/env_dreamer3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk/no_backup/jk639/env_dreamer3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/disk/no_backup/jk639/env_dreamer3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk/no_backup/jk639/env_dreamer3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x66048 and 4608x512)
```

**Comment by NM512** [comment]
I have made it possible to handle images with sizes that are powers of 2, so could you like to give it a try?

**Comment by NM512** [comment]
I made it possible to handle images of power-of-2 sizes (128, 256, ...), so why not give it a try?

**Comment by NM512** [comment]
I made it possible to handle images of power-of-2 sizes, so could you give it a try?

**Comment by alaliqing** [comment]
Now it works! Thank you!
