### ISSUE TITLE
Example from README not working

### ISSUE THREAD

**Issue by StuartShanks** [NM512/dreamerv3-torch#27]
Hi, I tried to train the example on DMC Vision but got the following error:

python3 dreamer.py --configs dmc_vision --task dmc_walker_walk --logdir ./logdir/dmc_walker_walk
Logdir logdir/dmc_walker_walk
Create envs.
libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

Traceback (most recent call last):
  File "/home/stuart/Github/dreamerv3-torch/dreamer.py", line 418, in <module>
    main(parser.parse_args(remaining))
  File "/home/stuart/Github/dreamerv3-torch/dreamer.py", line 332, in main
    train_envs = [make("train") for _ in range(config.envs)]
  File "/home/stuart/Github/dreamerv3-torch/dreamer.py", line 332, in <listcomp>
    train_envs = [make("train") for _ in range(config.envs)]
  File "/home/stuart/Github/dreamerv3-torch/dreamer.py", line 331, in <lambda>
    make = lambda mode: make_env(config, logger, mode, train_eps, eval_eps)
  File "/home/stuart/Github/dreamerv3-torch/dreamer.py", line 190, in make_env
    env = dmc.DeepMindControl(task, config.action_repeat, config.size)
  File "/home/stuart/Github/dreamerv3-torch/envs/dmc.py", line 11, in __init__
    from dm_control import suite
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/suite/__init__.py", line 24, in <module>
    from dm_control.suite import acrobot
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/suite/acrobot.py", line 20, in <module>
    from dm_control import mujoco
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 41, in <module>
    from dm_control import _render
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/_render/__init__.py", line 86, in <module>
    Renderer = import_func()
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/_render/__init__.py", line 36, in _import_egl
    from dm_control._render.pyopengl.egl_renderer import EGLContext
  File "/home/stuart/miniconda3/envs/dreamer3.9/lib/python3.9/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 75, in <module>
    raise ImportError('Cannot initialize a headless EGL display.')
ImportError: Cannot initialize a headless EGL display.

**Comment by NM512** [comment]
@StuartShanks

Hello,

It seems like the error is related to the rendering of DMC (DeepMind Control). You might find a solution by referring to [this issue](https://github.com/deepmind/dm_control/issues/123) on GitHub. It could be beneficial in resolving the problem you encountered.
